//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class call
    {
        public long CallId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Line { get; set; }
        public string Type { get; set; }
        public string Indicator { get; set; }
        public string Duration { get; set; }
        public string Checksum { get; set; }
        public string Rings { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
    }
}
