//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class caller_data
    {
        public int id { get; set; }
        public Nullable<int> dispacher_id { get; set; }
        public string pickup_address { get; set; }
        public string Line { get; set; }
        public string dropoff_address { get; set; }
        public string telephone { get; set; }
        public Nullable<int> LocalTripId { get; set; }
    
        public virtual triplog triplog { get; set; }
    }
}
