//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int id { get; set; }
        public string device_unique_code { get; set; }
        public string android_id { get; set; }
        public Nullable<int> dispacher_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string remarks { get; set; }
        public Nullable<int> assignment { get; set; }
        public Nullable<int> is_login { get; set; }
        public Nullable<int> on_trip { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> send_notification { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> send_push { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    }
}
