//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispacher
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string business_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public Nullable<int> state_id { get; set; }
        public string other_state { get; set; }
        public Nullable<int> country_id { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string zip_code { get; set; }
        public Nullable<long> contact_phone { get; set; }
        public string send_trip_option { get; set; }
        public Nullable<int> set_notification { get; set; }
        public Nullable<int> notification_time_in_min { get; set; }
        public string default_car_no { get; set; }
    }
}
