//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispacher_trips
    {
        public int id { get; set; }
        public Nullable<int> trip_id { get; set; }
        public Nullable<int> dispatcher_id { get; set; }
        public Nullable<int> trip_unique_id { get; set; }
    }
}
