//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int id { get; set; }
        public Nullable<int> dispatcher_id { get; set; }
        public string unique_code { get; set; }
        public string email { get; set; }
        public string license_number { get; set; }
        public string routing_no { get; set; }
        public string shift { get; set; }
        public string vat_number { get; set; }
        public Nullable<byte> status { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_number { get; set; }
        public string address { get; set; }
        public string account_no { get; set; }
    }
}
