//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_logs
    {
        public int id { get; set; }
        public string device_id { get; set; }
        public string trip_id { get; set; }
        public string android_id { get; set; }
        public string status { get; set; }
        public string trip_accepted_status { get; set; }
        public string trip_accepted_time { get; set; }
    }
}
