//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public Nullable<int> WebTripLogID { get; set; }
        public Nullable<int> DispatcherTripWebId { get; set; }
        public string DispatcherTripStatus { get; set; }
        public Nullable<int> DispatcherTripIsReservation { get; set; }
        public string pickup_address { get; set; }
        public string pickup_date { get; set; }
        public string pickup_time { get; set; }
        public string dropoff_address { get; set; }
        public string car_no { get; set; }
        public string DirectNotificationTime { get; set; }
        public string NotificationDateTime { get; set; }
        public string SendOrder { get; set; }
        public string DeviceId { get; set; }
        public string Created { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DispatcherId { get; set; }
        public Nullable<int> AmtOfPassengers { get; set; }
        public string Telephone { get; set; }
        public string Details { get; set; }
        public string Price { get; set; }
        public string VoucherNo { get; set; }
        public string AccountNo { get; set; }
        public string IsAdded { get; set; }
        public string IsUpdated { get; set; }
        public string Guid { get; set; }
    }
}
