//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class triplog
    {
        public triplog()
        {
            this.caller_data = new HashSet<caller_data>();
        }
    
        public int id { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> dispacher_id { get; set; }
        public string session_id { get; set; }
        public string pickup_address { get; set; }
        public string pickup_date { get; set; }
        public string pickup_time { get; set; }
        public string dropoff_address { get; set; }
        public string car_no { get; set; }
        public string telephone { get; set; }
        public Nullable<int> amt_of_passengers { get; set; }
        public string price { get; set; }
        public string details { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> tozone_id { get; set; }
        public Nullable<decimal> miles { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.TimeSpan> pickup_timing { get; set; }
        public Nullable<System.DateTime> dropoff_timing { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string payment_method { get; set; }
        public string ccard_no { get; set; }
        public string ccard_expirydate { get; set; }
        public string cvv { get; set; }
        public Nullable<decimal> total_paid_amount { get; set; }
        public string pickup_lat { get; set; }
        public string pickup_lng { get; set; }
        public string account_no { get; set; }
        public string voucher_no { get; set; }
        public string C_trip_created_ { get; set; }
        public Nullable<int> auto_complete { get; set; }
        public Nullable<int> fare_count { get; set; }
        public string created { get; set; }
        public string ActualPickUpAddress { get; set; }
        public string IsUpdated { get; set; }
        public Nullable<int> WebTripLogID { get; set; }
        public string IsCancelled { get; set; }
        public string IsAutoCompleted { get; set; }
        public string IsSentToDatabase { get; set; }
        public string uu_tripId { get; set; }
        public int reservation_status { get; set; }
        public string CC_cardnumber { get; set; }
        public string ProcessType { get; set; }
        public string TelephoneLine { get; set; }
        public string AcceptedTime { get; set; }
        public Nullable<int> DispatcherTripStatus { get; set; }
        public Nullable<int> DispatcherTripReservationStatus { get; set; }
        public string DirectNotificationTime { get; set; }
        public Nullable<int> TripCreated { get; set; }
        public Nullable<int> AssignedDispacherId { get; set; }
        public string Guid { get; set; }
    
        public virtual ICollection<caller_data> caller_data { get; set; }
    }
}
