//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public int id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> from_zone_id { get; set; }
        public Nullable<int> to_zone_id { get; set; }
        public Nullable<decimal> miles { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> pickup_timing { get; set; }
        public Nullable<System.DateTime> drop_timing { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
