//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class url_sends
    {
        public int id { get; set; }
        public string IO { get; set; }
        public string Line { get; set; }
        public string SE { get; set; }
        public string Duration { get; set; }
        public string RingType { get; set; }
        public string RingNumber { get; set; }
        public string Time { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string CallStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string Company { get; set; }
        public string Date { get; set; }
        public Nullable<int> StartId { get; set; }
    }
}
