//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerIdIntegration.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int id { get; set; }
        public Nullable<int> dipatcher_id { get; set; }
        public Nullable<int> cab_id { get; set; }
        public string vehicle_unique_id { get; set; }
        public string vehicle_name { get; set; }
        public string vehicle_number { get; set; }
        public string driver_name { get; set; }
        public Nullable<int> assignment { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
